#!/usr/local/bin/python
#Web Service for tab separated values
#27 Feb 2011
#Author: Gunnar Leffler

import sys,os,time,datetime
import cx_Oracle
sys.path.append("/usr/dd/common/web_service/webexec")
import cgi,wslib,atexit
import cgitb;cgitb.enable()

ws = wslib.ddWebService()
config = wslib.ddWebServiceConfig()

def outputTSV (config):
  maxLen = 0
  wsData = []
  print "Content-Type: text/plain\n"
  #read the data and find the max length
  output = ""
  for tsid in config.settings["id"]:
    t = ws.readTS(tsid[0],config.settings["start"],config.settings["end"],tsid[1])
    if t != None:
      if len(t) > maxLen: maxLen = len(t)
      if "interpolate" in config.settings:
        ts = wslib.timeSeries(t)
        interval = ts.parseTimedelta(config.settings["interpolate"])
        if interval >= datetime.timedelta(seconds=30): #We don't want an absurd interval to tie up system resources
          t = ts.interpolate(interval).data
      if "snap" in config.settings:
        ts = wslib.timeSeries(t)
        interval = ts.parseTimedelta(config.settings["snap"])
        if interval >= datetime.timedelta(seconds=30): #We don't want an absurd interval to tie up system resources
          t = ts.snap(interval,interval/2).data
      if "hardsnap" in config.settings:
        ts = wslib.timeSeries(t)
        interval = ts.parseTimedelta(config.settings["hardsnap"])
        if interval >= datetime.timedelta(seconds=30): #We don't want an absurd interval to tie up system resources
          try:
            t1 = ts.data[0][0]
            t2 = datetime.datetime(year=t1.year,month=t1.month,day=t1.day)
            t = ts.snap(interval,interval/2,starttime=t2).data
          except:
            t = []
      if "average" in config.settings:
        ts = wslib.timeSeries(t)
        interval = ts.parseTimedelta(config.settings["average"])
        if interval >= datetime.timedelta(seconds=30): #We don't want an absurd interval to tie up system resources
          t = ts.average(interval).data
      if "maximum" in config.settings:
        ts = wslib.timeSeries(t)
        interval = ts.parseTimedelta(config.settings["maximum"])
        t = ts.maxmin(interval,lambda x,y:x>y).data
      if "minimum" in config.settings:
        ts = wslib.timeSeries(t)
        interval = ts.parseTimedelta(config.settings["minimum"])
        t = ts.maxmin(interval,lambda x,y:x<y).data
    else:
      t = []
    wsData.append(t)
    output += "timestamp\t"+tsid[0]+"["+tsid[1]+"]"+"\t"
  print output
  #display the data
  for i in xrange(0,maxLen):
    output = ""
    for d in wsData:
      if i < len(d):
        if d[i][1] != None:
          output += "%s\t%0.3f\t"%(d[i][0].strftime(config.settings["timeformat"]),d[i][1])
        else:
          output+= "%s\t\t"%(d[i][0].strftime(config.settings["timeformat"]))
      else:
        output+= ("\t\t")
    print output[0:-1]

#------------------------#
#Beginning of Service
#------------------------#
config.loadConfig("../config/config.json")
ws.updateConfig(config)
ws.connect()
if ws.status != "OK":
  raise Exception(ws.status)
atexit.register(ws.disconnect)
config.parseParameters(cgi.FieldStorage())
outputTSV(config)
